BEGIN;

CREATE SEQUENCE IF NOT EXISTS keys_id_seq;
CREATE SEQUENCE IF NOT EXISTS users_id_seq;

CREATE TABLE IF NOT EXISTS tg_users (
  id BIGSERIAL PRIMARY KEY,
  user_id VARCHAR(12) NOT NULL,
  free BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS wallets (
  id BIGSERIAL PRIMARY KEY,
  address VARCHAR(64) NOT NULL,
  secret_key VARCHAR(64) NOT NULL,
  tg_user_id BIGINT,
  balance DECIMAL(10, 2) DEFAULT 0,
  FOREIGN KEY (tg_user_id) REFERENCES tg_users(id)
);



END;

